---
device: "/dev/sdb"
dev_size: "90g"
vg_name: "vault"
lv_name: "data"
logical_device: "/dev/vault/data"
dir_mount:
  - "/vault"
  - "/vault/data"
path_mount: "/vault/data"


# pvcreate /dev/sdb
# vgcreate data /dev/sdb
# lvcreate -n ibm -L 25G data
# mkfs.ext4 /dev/data/ibm
# mkdir /ibm
# mount /dev/data/ibm /ibm/