---
listener_tcp_address: "0.0.0.0"
listener_tcp_port: "8200"
cluster_address: "{{ ansible_host }}"
cluster_port: "8201"
tls_disable: true
storage: "consul"
storage_address: "0.0.0.0"
storage_port: "8500"
storage_path: "vault/"
api_addr: "http://{{ inventory_hostname }}"
cluster_addr: "https://{{ inventory_hostname }}"