---
- name: Add Hashicorp Repo
  yum_repository:
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgcheck: yes
    enabled: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Get stats of the Vault Download
  package:
    name: vault
    state: latest

- name: Copy the Vault configuration file
  template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    backup: yes
  notify: Start the Vault service

- name: "Ajust Certificates Permission"
  file:
    state: directory
    path: "{{ path_certificate }}"
    owner: vault
    group: vault
    recurse: yes
    mode: 0644

- name: "Ajust Directory Permission"
  file:
    state: directory
    path: "{{ item }}"
    owner: vault
    group: vault
    mode: 0755
  loop:
    - "{{ data_dir }}"
    - "{{ path_certificate }}"

- name: Start the Vault service
  service:
    name: vault
    state: started
    enabled: yes